on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master

      # Auto commits minified files to the repository
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: gh_pages
